### ISSUE TITLE
Embeddings are broken

### ISSUE THREAD

**Issue by amaxcz** [Dev317/streamlit_chromadb_connection#8]
for example trying to use OpenAIEmbeddingFunction

configuration = {
            "client": "PersistentClient",
            "path": "./db1"
        }
chroma_conn = st.connection("chromadb", type=ChromadbConnection, **configuration)

chroma_conn.create_collection(
            collection_name=HISTORY_COLLECTION,
            embedding_function_name="OpenAIEmbeddingFunction",
            embedding_config={
                "api_key": st.secrets.openai.api_key,
                "organization_id": st.secrets.openai.organization
            },
        )

<chromadb.utils.embedding_functions.OpenAIEmbeddingFunction object at 0x784024026ab0>        
but if doing
    metadata = {"type": "human"}
    chroma_conn.upload_documents(
        collection_name=HISTORY_COLLECTION,
        documents=[user_query],
        metadatas=[metadata],
        ids=[message_id]
    )        

in the method
def upload_documents(self,
                        collection_name: str,
                        documents: List,
                        metadatas: List,
                        ids: List,
                        embeddings: List = None) -> None:
    here:
embedding = collection._embedding_function([doc])

    it returns
<chromadb.utils.embedding_functions.ONNXMiniLM_L6_V2 object at 0x78403cb04110>

so, thats wrong, looks like it broken while saves collection embedding functions

====
p.s. only default embeddings works now.

**Comment by Dev317** [comment]
Hmm, I think the issue lies in `chromadb` source code itself. In `chromadb/api/client.py`, there is no storage of what embedding function that the collection used. The `Collection`'s embedding function is only initialized based on the embedding_function param passed in. Else, it would just default to the ONNXMiniLM_L6_V2 embedding function.

```
@override
    def get_collection(
        self,
        name: str,
        id: Optional[UUID] = None,
        embedding_function: Optional[
            EmbeddingFunction[Embeddable]
        ] = ef.DefaultEmbeddingFunction(),  # type: ignore
        data_loader: Optional[DataLoader[Loadable]] = None,
    ) -> Collection:
        model = self._server.get_collection(
            id=id,
            name=name,
            tenant=self.tenant,
            database=self.database,
        )
        return Collection(
            client=self._server,
            model=model,
            embedding_function=embedding_function,
            data_loader=data_loader,
        )

```

From my end, there is only 1 thing I can do is to enforce that in `upload_documents()`, one must pass in the name of the embedding function to at least ensure consistency

**Comment by amaxcz** [comment]
also, be sure that (an example, raw code):

def create_collection(self, collection_name):
        try:
            metadata = {"hnsw:space": "cosine"}
            return self.db.create_collection(
                name=collection_name,
                embedding_function=self.embedding_function,
                metadata=metadata
            )
        except Exception as e:
            return self.db.get_collection(collection_name, 
embedding_function=self.embedding_function)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                                               
so, if we get existing collection, we need to specify embedding.

**Comment by amaxcz** [comment]
ah, ok, now I see new fix ( enforcing embedding_function while getting collection).

**Comment by maximilianzuern** [comment]
The same issue applies and is still present when using a locally stored database with PersistentClient and querying it.
Here, the default embedding model is used to embed the query, which is not coherent with the embedding model used to embed the documents.

```python
Exception: Error while querying collection `TestBGEbase`: Embedding dimension 384 does not match collection dimensionality 768

File "/opt/homebrew/Caskroom/miniconda/base/envs/py311/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
File "/Users/max/Downloads/streamlitCoT.py", line 325, in <module>
    main()
File "/Users/max/Downloads/streamlitCoT.py", line 240, in main
    results_df = conn.query(
                 ^^^^^^^^^^^
File "/opt/homebrew/Caskroom/miniconda/base/envs/py311/lib/python3.11/site-packages/streamlit_chromadb_connection/chromadb_connection.py", line 275, in query
    raise Exception(f"Error while querying collection `{collection_name}`: {str(exception)}")
``` 
---

When using chromaDB, I specified the embedding function while calling `get_collection()`: 

```python
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction

ef = SentenceTransformerEmbeddingFunction(model_name="BAAI/bge-base-en-v1.5", trust_remote_code=True, device="mps")

collection = chroma_client.get_collection(
    name="TestBGEbase",
    embedding_function=ef,
    )
```
